import Link from "next/link";

const products = [
 {name:"Auriculares Bluetooth",price:4999,cost:1850,category:"Tecnologia",icon:"🎧"},
 {name:"Candeeiro LED USB",price:4499,cost:1400,category:"Casa",icon:"💡"},
 {name:"Kit de Bandas de Resistência",price:2999,cost:800,category:"Fitness",icon:"🏋️"},
 {name:"Tote Bag Minimalista",price:2499,cost:580,category:"Moda",icon:"👜"}
];
const featuredProduct = products[0];
const formatPrice = (cents: number) => new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" }).format(cents / 100);

export default function Home(){return <main><header className="topbar"><div className="container nav"><div className="logo">Global<span>Drops</span></div><nav><a href="#produtos">Produtos</a><a href="#como-funciona">Como funciona</a><Link className="login-link" href="/login">Entrar</Link><Link className="button small" href="/cadastro">Começar grátis</Link></nav></div></header><section className="hero"><div className="container hero-grid"><div><div className="badge">🌍 Marketplace global para revendedores</div><h1>Encontra produtos.<br/><span>Revende. Cresce.</span></h1><p className="lead">Descobre produtos de fornecedores, define a tua margem e cria a tua própria loja online.</p><div className="actions"><Link className="button" href="/cadastro">Começar grátis</Link><a className="button ghost" href="#como-funciona">Ver como funciona</a></div></div><div className="hero-card"><div className="card-top"><span>Margem antes de despesas</span><strong>+ {formatPrice(featuredProduct.price - featuredProduct.cost)}</strong></div><div className="product-preview"><div className="product-icon">🎧</div><div><strong>{featuredProduct.name}</strong><small>Fornecedor: TechVault</small></div></div><div className="numbers"><span>Custo <b>{formatPrice(featuredProduct.cost)}</b></span><span>Venda <b>{formatPrice(featuredProduct.price)}</b></span></div></div></div></section><section id="produtos" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">CATÁLOGO</div><h2>Produtos para começares</h2></div><Link href="/cadastro">Ver catálogo →</Link></div><div className="grid">{products.map(p=><article className="product" key={p.name}><div className="product-image">{p.icon}</div><div className="product-body"><small>{p.category}</small><h3>{p.name}</h3><div className="price-row"><strong>{formatPrice(p.price)}</strong><span>custo {formatPrice(p.cost)}</span></div><Link href="/cadastro" className="product-link">Adicionar à minha loja →</Link></div></article>)}</div></div></section><section id="como-funciona" className="how"><div className="container"><div className="eyebrow">COMO FUNCIONA</div><h2>Uma forma simples de começar</h2><div className="steps"><div><b>01</b><h3>Cria a tua conta</h3><p>Regista-te gratuitamente como revendedor.</p></div><div><b>02</b><h3>Escolhe produtos</h3><p>Explora o catálogo e define a tua margem.</p></div><div><b>03</b><h3>Vende online</h3><p>Usa a tua loja para receber encomendas.</p></div></div></div></section><footer><div className="container footer"><div className="logo">Global<span>Drops</span></div><span>© 2026 GlobalDrops</span></div></footer></main>}
